### ISSUE TITLE
Improve `meson test`

### ISSUE THREAD

**Issue by bonzini** [mesonbuild/meson#7830]
I would like to work on improving `meson test` so that it can replace QEMU's homegrown test harness (which is based on introspection) and be the best test harness for C. :) Here are some wishlist items:

- [x] `meson test` with a specific test should only build what is needed for the test (#7902)
- [x] immediately interrupt a test when ^C is pressed (#7836)
  - [x] interrupt whole run if ^C is pressed several times in a row (#8201)
- [x] introduce a progress report/spinner
  - [x] whenever multiple tests are running, update the status of the running tests every second (similar to `yum` for example) (#8001)
  - [x] print a summary of TAP subtests as they are run (#8029)
- [x] include stdout/stderr even when using verbose mode (#8225)
- [x] improve looks and usefulness of console output (#8200)
  - [x] print reproducer command line for each failed test right below the test
  - [x] do not mix the output of multiple tests in verbose mode
  - [x] print command line as soon as each test is started when invoked with `-v --num-processes 1`
  - [x] print each failing test's output right below the test
  - [x] report on TAP subtests as they are encountered (failing subtests only if not in verbose mode)

[Here is a mockup](https://asciinema.org/a/fTPIywXwPjwXjznR0iFvitrMu).

The plan is to replace TestHarness's output layer with an event-based ("observer") interface driven mostly by SingleTestRunner. `SingleTestRunner` and `TestRun.make_tap` will send events to the harness, which will therefore be able to observe TAP subtests as they happen. Because the harness is based on `asyncio`, it can also do background updates to the UI every second in addition to writing the various logfiles.

The [code for the mockup](https://gist.github.com/bonzini/2b1a7bb332491ade558985ed0ff1405c) uses `asyncio` in order to show (very roughly!) what the `meson test` code would look like.
